data_dir: /develop/data/WildfireSpreadTS_HDF5/
batch_size: 64
n_leading_observations: 1
crop_side_length: 128
load_from_hdf5: true
num_workers: 20
remove_duplicate_features: false
features_to_keep: null
n_leading_observations_test_adjustment: 5