accelerator: gpu
strategy: auto
devices: 1
num_nodes: 1
precision: 32-true
logger: 
  class_path: pytorch_lightning.loggers.wandb.WandbLogger
  init_args:
    # Determined via argument linking in train.py
    # save_dir: ${fit.trainer.default_root_dir}
    project: wildfire-resnet18-domainadaptation
    log_model: true

enable_checkpointing: true
# callbacks: 
#   - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
#     init_args:
#       monitor: train_loss
#       mode: min
#       save_top_k: 1
#       save_last: false
#       filename: "best-{epoch:02d}-{train_loss:.4f}"
  
#   # Always save last epoch
#   - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
#     init_args:
#       save_last: true
#       filename: "last" 


callbacks: 
  - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
    init_args:
      # Monitor entropy loss logged on_epoch by IWANStage3_Adaptation
      monitor: train_loss_entropy 
      mode: min
      save_top_k: 1
      save_last: false
      filename: "best-adapted-{epoch:02d}-{train_loss_entropy:.4f}"
  
  - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
    init_args:
      save_last: true
      filename: "last"


fast_dev_run: false
max_epochs: 3
min_epochs: -1
max_steps: -1
min_steps: -1
max_time: null
limit_train_batches: null
limit_val_batches: 0
limit_test_batches: null
limit_predict_batches: null
overfit_batches: 0.0 # off
val_check_interval: null
check_val_every_n_epoch: 0
num_sanity_val_steps: 0
log_every_n_steps: null
enable_progress_bar: true
enable_model_summary: null
accumulate_grad_batches: 1
gradient_clip_val: null
gradient_clip_algorithm: null
deterministic: warn
benchmark: false
inference_mode: false
use_distributed_sampler: true
profiler: null
detect_anomaly: false
barebones: false
plugins: null
sync_batchnorm: false
reload_dataloaders_every_n_epochs: 0
default_root_dir: /develop/results/
