seed_everything: 0
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
model:
  class_path: models.SegFormerModel
  init_args:
    model_name: "nvidia/segformer-b0-finetuned-ade-512-512"   # ✅ official pretrained SegFormer backbone
    n_channels: 8
    flatten_temporal_dimension: true
    pos_class_weight: 236 # (relative frequency in augmented 2018 and 2020 fires)^-1
    loss_function: Focal
    #alpha_focal: 0.1

do_train: true
do_predict: false
do_test: true