apiVersion: batch/v1
kind: Job
metadata:
  name: sameep-veg-monotemporal-job
  namespace: gp-engine-malof
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sameep-veg-monotemporal
          image: docker.io/saadlahrichi/fire:v6
          imagePullPolicy: IfNotPresent
          workingDir: /develop/code
          env:
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb-secret-sameep
                  key: api-key
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "ðŸ“¦ Cloning the code..."
              rm -rf /develop/code/WildfireSpreadTS
              git clone https://github.com/sameep-dhakal/WildfireSpreadTS.git
              cd WildfireSpreadTS

              echo "ðŸ” Logging into W&B"
              wandb login $WANDB_API_KEY

              echo "ðŸš€ Launching sweep"
              SWEEP_AGENT_CMD=$(wandb sweep cfgs/unet/wandb_veg_features_only.yaml --name sameep_swin_sweep 2>&1 | grep "wandb: Run sweep agent with:" | sed 's/wandb: Run sweep agent with: //')
              echo "ðŸ‘‰ Running: $SWEEP_AGENT_CMD"
              eval "$SWEEP_AGENT_CMD"
          resources:
            limits:
              memory: 150Gi
              cpu: 20
              nvidia.com/gpu: 1
            requests:
              memory: 150Gi
              cpu: 20
              nvidia.com/gpu: 1
          volumeMounts:
            - name: fire-data
              mountPath: /develop/data
            - name: sameep-code
              mountPath: /develop/code
            - name: sameep-results
              mountPath: /develop/results
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: fire-data
          persistentVolumeClaim:
            claimName: fire-data
        - name: sameep-code
          persistentVolumeClaim:
            claimName: sameep-code
        - name: sameep-results
          persistentVolumeClaim:
            claimName: sameep-results
        - name: shm
          emptyDir:
            medium: Memory
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/gp-engine-malof"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/issue"
          operator: "Exists"
          effect: "NoSchedule"
  backoffLimit: 0
