project: office31-partial-da-iwan
program: src/models/DomainAdpatation/train_iwan_officehome.py
command:
  - ${env}
  - python3
  - ${program}
  - ${args}

method: grid
metric:
  name: tgt_acc_post_da
  goal: maximize

parameters:
  data_root: {value: /develop/data/Office-31}
  list_root: {value: /develop/data/Office-31}   # ✅ add this


  source: {values: [amazon, dslr, webcam]}
  target: {values: [amazon, dslr, webcam]}

  test_ratio: {value: 0.3}     # important for table-like evaluation
  split_seed: {value: 42}

  arch: {value: alexnet}
  bottleneck_dim: {value: 256}
  batch_size: {value: 64}
  num_workers: {value: 4}

  epochs_cls: {value: 200}
  epochs_da: {value: 250}
  lr_cls: {value: 0.001}
  lr_da: {value: 0.001}

  patience_cls: {value: 0}
  patience_da: {value: 0}

  lambda_upper: {value: 0.1}
  alpha: {value: 10.0}
  entropy_weight: {values: [0.0, 0.01, 0.1]}
