project: officehomedataset-domainadaptation
program: src/models/DomainAdpatation/train_iwan_officehome.py
command:
  - ${env}
  - python3
  - ${program}
  - ${args}
method: grid
metric:
  name: tgt_acc_post_da
  goal: maximize
parameters:
  data_root: {value: /develop/data/OfficeHomeDataset}
  source: {value: Product}
  target: {value: "Real World"}
  batch_size: {value: 64}
  epochs_cls: {value: 200}
  epochs_da: {value: 250}
  lr: {values: [0.0001, 0.00001]}
  lambda_upper: {value: 0.1}
  entropy_weight: {values: [0.0, 0.01, 0.05, 0.1]}
  alpha: {value: 1.0}
  arch: {value: resnet50}
  bottleneck_dim: {value: 256}
  patience_cls: {value: 20}
  patience_da: {value: 0}
