project: office31-partial-da-iwan-baseline
program: src/models/DomainAdpatation/train_iwan_officehome.py
command:
  - ${env}
  - python3
  - ${program}
  - ${args}

method: grid
metric:
  name: tgt_acc_post_da
  goal: maximize

parameters:
  data_root: {value: /develop/data/Office-31}
  source: {values: [amazon]}
  target: {values: [webcam]}

  batch_size: {value: 64}
  num_workers: {value: 4}
  seed: {value: 42}

  partial_mode: {value: office_caltech_10}

  epochs_cls: {value: 80}
  lr_cls: {values: [0.0001]}

  epochs_da: {value: 25}
  lr_da: {values: [0.0001]}

  lambda_upper: {value: 0.1}
  alpha: {values: [10.0]}
  entropy_weight: {values: [0.0]}

  src_val_ratio: {value: 0.1}
